# -*- coding: utf-8 -*-
"""
작업 상태값과 오류 코드를 이 파일 한 곳에서만 정의한다.
다른 모듈은 상태 문자열을 직접 하드코딩하지 말고 이 상수를 가져다 쓴다.
"""

# ---- 사용자 ----
USER_ROLE_USER = "user"
USER_ROLE_ADMIN = "admin"
USER_ROLES = (USER_ROLE_USER, USER_ROLE_ADMIN)

USER_STATUS_ACTIVE = "active"
USER_STATUS_INACTIVE = "inactive"
USER_STATUSES = (USER_STATUS_ACTIVE, USER_STATUS_INACTIVE)

# ---- 프로젝트(제작 작업) 상태 ----
PROJECT_STATUS_DRAFT = "draft"                    # 입력 단계
PROJECT_STATUS_GENERATING_CONTENT = "generating_content"   # SNS 8채널 원고 생성 중
PROJECT_STATUS_GENERATING_MEDIA = "generating_media"       # 음성/자막 생성 중
PROJECT_STATUS_RENDERING_VIDEO = "rendering_video"         # MP4 렌더링 중
PROJECT_STATUS_SELECTING_THUMBNAIL = "selecting_thumbnail" # 썸네일 선택 대기
PROJECT_STATUS_COMPLETED = "completed"
PROJECT_STATUS_FAILED = "failed"

PROJECT_STATUSES = (
    PROJECT_STATUS_DRAFT,
    PROJECT_STATUS_GENERATING_CONTENT,
    PROJECT_STATUS_GENERATING_MEDIA,
    PROJECT_STATUS_RENDERING_VIDEO,
    PROJECT_STATUS_SELECTING_THUMBNAIL,
    PROJECT_STATUS_COMPLETED,
    PROJECT_STATUS_FAILED,
)

# ---- 오류 코드 ----
ERROR_NONE = ""
ERROR_AI_PROVIDER_FAILED = "AI_PROVIDER_FAILED"
ERROR_MEDIA_RENDER_FAILED = "MEDIA_RENDER_FAILED"
ERROR_STORAGE_WRITE_FAILED = "STORAGE_WRITE_FAILED"
ERROR_VALIDATION_FAILED = "VALIDATION_FAILED"
ERROR_QUOTA_EXCEEDED = "QUOTA_EXCEEDED"
ERROR_UNKNOWN = "UNKNOWN_ERROR"

ERROR_CODES = (
    ERROR_NONE,
    ERROR_AI_PROVIDER_FAILED,
    ERROR_MEDIA_RENDER_FAILED,
    ERROR_STORAGE_WRITE_FAILED,
    ERROR_VALIDATION_FAILED,
    ERROR_QUOTA_EXCEEDED,
    ERROR_UNKNOWN,
)

# ---- 보관함 미디어 종류 ----
MEDIA_TYPE_IMAGE = "image"
MEDIA_TYPE_AUDIO = "audio"
MEDIA_TYPE_SUBTITLE = "subtitle"
MEDIA_TYPE_VIDEO = "video"
MEDIA_TYPE_THUMBNAIL = "thumbnail"

MEDIA_TYPES = (
    MEDIA_TYPE_IMAGE,
    MEDIA_TYPE_AUDIO,
    MEDIA_TYPE_SUBTITLE,
    MEDIA_TYPE_VIDEO,
    MEDIA_TYPE_THUMBNAIL,
)
