# -*- coding: utf-8 -*-
"""
작업 상태값과 오류 코드를 이 파일 한 곳에서만 정의한다.
다른 모듈은 상태 문자열을 직접 하드코딩하지 말고 이 상수를 가져다 쓴다.
"""

# ---- 사용자 ----
USER_ROLE_USER = "user"
USER_ROLE_ADMIN = "admin"
USER_ROLES = (USER_ROLE_USER, USER_ROLE_ADMIN)

USER_STATUS_ACTIVE = "active"
USER_STATUS_INACTIVE = "inactive"
USER_STATUSES = (USER_STATUS_ACTIVE, USER_STATUS_INACTIVE)

# ---- 프로젝트(제작 작업) 상태 ----
# 단계5 이후 상세계획서(2026-07-29)의 상태 머신을 그대로 채택한다.
PROJECT_STATUS_DRAFT = "draft"
PROJECT_STATUS_QUEUED = "queued"
PROJECT_STATUS_PROMPTING = "prompting"
PROJECT_STATUS_GENERATING = "generating"
PROJECT_STATUS_VALIDATING = "validating"
PROJECT_STATUS_CONTENT_READY = "content_ready"
PROJECT_STATUS_TTS_READY = "tts_ready"
PROJECT_STATUS_SUBTITLE_READY = "subtitle_ready"
PROJECT_STATUS_MEDIA_READY = "media_ready"
PROJECT_STATUS_RENDERING = "rendering"
PROJECT_STATUS_COMPLETED = "completed"
PROJECT_STATUS_FAILED = "failed"

PROJECT_STATUSES = (
    PROJECT_STATUS_DRAFT,
    PROJECT_STATUS_QUEUED,
    PROJECT_STATUS_PROMPTING,
    PROJECT_STATUS_GENERATING,
    PROJECT_STATUS_VALIDATING,
    PROJECT_STATUS_CONTENT_READY,
    PROJECT_STATUS_TTS_READY,
    PROJECT_STATUS_SUBTITLE_READY,
    PROJECT_STATUS_MEDIA_READY,
    PROJECT_STATUS_RENDERING,
    PROJECT_STATUS_COMPLETED,
    PROJECT_STATUS_FAILED,
)

# ---- 오류 코드 ----
ERROR_NONE = ""
ERROR_AI_PROVIDER_FAILED = "AI_PROVIDER_FAILED"
ERROR_MEDIA_RENDER_FAILED = "MEDIA_RENDER_FAILED"
ERROR_STORAGE_WRITE_FAILED = "STORAGE_WRITE_FAILED"
ERROR_VALIDATION_FAILED = "VALIDATION_FAILED"
ERROR_QUOTA_EXCEEDED = "QUOTA_EXCEEDED"
ERROR_UNKNOWN = "UNKNOWN_ERROR"

ERROR_CODES = (
    ERROR_NONE,
    ERROR_AI_PROVIDER_FAILED,
    ERROR_MEDIA_RENDER_FAILED,
    ERROR_STORAGE_WRITE_FAILED,
    ERROR_VALIDATION_FAILED,
    ERROR_QUOTA_EXCEEDED,
    ERROR_UNKNOWN,
)

# ---- 보관함 미디어 종류 ----
MEDIA_TYPE_IMAGE = "image"
MEDIA_TYPE_AUDIO = "audio"
MEDIA_TYPE_SUBTITLE = "subtitle"
MEDIA_TYPE_VIDEO = "video"
MEDIA_TYPE_THUMBNAIL = "thumbnail"

MEDIA_TYPES = (
    MEDIA_TYPE_IMAGE,
    MEDIA_TYPE_AUDIO,
    MEDIA_TYPE_SUBTITLE,
    MEDIA_TYPE_VIDEO,
    MEDIA_TYPE_THUMBNAIL,
)
