# -*- coding: utf-8 -*-
"""
작업 상태값과 오류 코드를 이 파일 한 곳에서만 정의한다.
다른 모듈은 상태 문자열을 직접 하드코딩하지 말고 이 상수를 가져다 쓴다.
"""

# ---- 사용자 ----
USER_ROLE_USER = "user"
USER_ROLE_ADMIN = "admin"
USER_ROLES = (USER_ROLE_USER, USER_ROLE_ADMIN)

USER_STATUS_ACTIVE = "active"
USER_STATUS_INACTIVE = "inactive"
USER_STATUSES = (USER_STATUS_ACTIVE, USER_STATUS_INACTIVE)

# ---- 프로젝트(제작 작업) 상태 ----
# 단계5 이후 상세계획서(2026-07-29)의 상태 머신을 그대로 채택한다.
PROJECT_STATUS_DRAFT = "draft"
PROJECT_STATUS_QUEUED = "queued"
PROJECT_STATUS_PROMPTING = "prompting"
PROJECT_STATUS_GENERATING = "generating"
PROJECT_STATUS_VALIDATING = "validating"
PROJECT_STATUS_CONTENT_READY = "content_ready"
PROJECT_STATUS_TTS_READY = "tts_ready"
PROJECT_STATUS_SUBTITLE_READY = "subtitle_ready"
PROJECT_STATUS_MEDIA_READY = "media_ready"
PROJECT_STATUS_RENDERING = "rendering"
PROJECT_STATUS_COMPLETED = "completed"
PROJECT_STATUS_FAILED = "failed"

PROJECT_STATUSES = (
    PROJECT_STATUS_DRAFT,
    PROJECT_STATUS_QUEUED,
    PROJECT_STATUS_PROMPTING,
    PROJECT_STATUS_GENERATING,
    PROJECT_STATUS_VALIDATING,
    PROJECT_STATUS_CONTENT_READY,
    PROJECT_STATUS_TTS_READY,
    PROJECT_STATUS_SUBTITLE_READY,
    PROJECT_STATUS_MEDIA_READY,
    PROJECT_STATUS_RENDERING,
    PROJECT_STATUS_COMPLETED,
    PROJECT_STATUS_FAILED,
)

# ---- 오류 코드 ----
ERROR_NONE = ""
ERROR_AI_PROVIDER_FAILED = "AI_PROVIDER_FAILED"
ERROR_MEDIA_RENDER_FAILED = "MEDIA_RENDER_FAILED"
ERROR_STORAGE_WRITE_FAILED = "STORAGE_WRITE_FAILED"
ERROR_VALIDATION_FAILED = "VALIDATION_FAILED"
ERROR_QUOTA_EXCEEDED = "QUOTA_EXCEEDED"
ERROR_UNKNOWN = "UNKNOWN_ERROR"

ERROR_CODES = (
    ERROR_NONE,
    ERROR_AI_PROVIDER_FAILED,
    ERROR_MEDIA_RENDER_FAILED,
    ERROR_STORAGE_WRITE_FAILED,
    ERROR_VALIDATION_FAILED,
    ERROR_QUOTA_EXCEEDED,
    ERROR_UNKNOWN,
)

# ---- Gemini(및 향후 다른 Provider) 호출 오류 분류 ----
# 단계 6A 작업지시 9장의 13개 오류 상태를 그대로 채택한다.
GEMINI_ERR_API_KEY_MISSING = "api_key_missing"
GEMINI_ERR_AUTHENTICATION_FAILED = "authentication_failed"
GEMINI_ERR_PERMISSION_DENIED = "permission_denied"
GEMINI_ERR_TIMEOUT = "timeout"
GEMINI_ERR_RATE_LIMITED = "rate_limited"
GEMINI_ERR_PROVIDER_5XX = "provider_5xx"
GEMINI_ERR_NETWORK_ERROR = "network_error"
GEMINI_ERR_INVALID_JSON = "invalid_json"
GEMINI_ERR_SCHEMA_VALIDATION_FAILED = "schema_validation_failed"
GEMINI_ERR_EMPTY_RESPONSE = "empty_response"
GEMINI_ERR_BLOCKED_RESPONSE = "blocked_response"
GEMINI_ERR_DUPLICATE_REQUEST = "duplicate_request"
GEMINI_ERR_UNKNOWN_PROVIDER_ERROR = "unknown_provider_error"

GEMINI_ERROR_CODES = (
    GEMINI_ERR_API_KEY_MISSING,
    GEMINI_ERR_AUTHENTICATION_FAILED,
    GEMINI_ERR_PERMISSION_DENIED,
    GEMINI_ERR_TIMEOUT,
    GEMINI_ERR_RATE_LIMITED,
    GEMINI_ERR_PROVIDER_5XX,
    GEMINI_ERR_NETWORK_ERROR,
    GEMINI_ERR_INVALID_JSON,
    GEMINI_ERR_SCHEMA_VALIDATION_FAILED,
    GEMINI_ERR_EMPTY_RESPONSE,
    GEMINI_ERR_BLOCKED_RESPONSE,
    GEMINI_ERR_DUPLICATE_REQUEST,
    GEMINI_ERR_UNKNOWN_PROVIDER_ERROR,
)

# 자동 재시도를 허용하는 오류(작업지시 10장): timeout, 429, 일부 5xx, 일시적 network_error.
GEMINI_RETRYABLE_ERROR_CODES = (
    GEMINI_ERR_TIMEOUT,
    GEMINI_ERR_RATE_LIMITED,
    GEMINI_ERR_PROVIDER_5XX,
    GEMINI_ERR_NETWORK_ERROR,
)

GEMINI_MAX_RETRIES = 2
GEMINI_RETRY_BASE_DELAY_SECONDS = 2.0

PROMPT_VERSION = "6a-v1"
RESPONSE_SCHEMA_VERSION = "6a-test-v1"

# ---- 보관함 미디어 종류 ----
MEDIA_TYPE_IMAGE = "image"
MEDIA_TYPE_AUDIO = "audio"
MEDIA_TYPE_SUBTITLE = "subtitle"
MEDIA_TYPE_VIDEO = "video"
MEDIA_TYPE_THUMBNAIL = "thumbnail"

MEDIA_TYPES = (
    MEDIA_TYPE_IMAGE,
    MEDIA_TYPE_AUDIO,
    MEDIA_TYPE_SUBTITLE,
    MEDIA_TYPE_VIDEO,
    MEDIA_TYPE_THUMBNAIL,
)
